export const tableColumns = [
  { key: "name", title: "Name", icon: "calendar", width: "10%" },
  { key: "email", title: "Email", icon: "clients" },
  { key: "phone", title: "Phone", icon: "income" },
  { key: "address", title: "Address", icon: "expense" },
  { key: "company", title: "Company", icon: "calendarFact" },
];

export const tableData = Array.from({ length: 40 }, (_, index) => ({
  id: index + 1,
  name: `User ${index + 1}`,
  email: `user${index + 1}@example.com`,
  phone: `123-456-789${index % 10}`,
  address: `1234 Street ${index + 1}, City, Country`,
  company: `Company ${index + 1}`,
}));




export const mockDataClients = [
  {
    clientCode: "PBS2017",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2018",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2019",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2020",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2021",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2022",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2023",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2024",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2025",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2026",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2027",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2028",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2029",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2030",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2031",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2032",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2033",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2034",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2035",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2036",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2037",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2038",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2039",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2040",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2041",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2042",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2043",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2044",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2045",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2046",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2047",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2048",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2049",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2050",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2051",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2052",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2053",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2054",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2055",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2056",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2057",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2058",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2059",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2060",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2061",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2062",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2063",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2064",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2065",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2066",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2067",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2068",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2069",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2070",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2071",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2072",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2073",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2074",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2075",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2076",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2077",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2078",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2079",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2080",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2081",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2082",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2083",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2084",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2085",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2086",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2087",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2088",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2089",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2090",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2091",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2092",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2093",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2094",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2095",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2096",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2097",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2098",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2099",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2100",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2101",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2102",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2103",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2104",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2105",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2106",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2107",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2108",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2109",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2110",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2111",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2112",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2113",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2114",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2115",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12 Pro max 256 gb",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
  {
    clientCode: "PBS2116",
    clientName: "Maqsudov Nodir Xabibullayev",
    product: "iPhone 12",
    monthlyPayment: "$100",
    status: "paid",
    saleDate: "2024.11.01",
    executor: "You",
    term: "100 days",
  },
];
