import {
  Calendar,
  Clients,
  Dashboard,
  Leads,
  Products,
  ToggleClose,
  ToggleOpen,
  Search,
  Telephone,
  Notification,
  TickCircle,
  Close,
  CloseCircle,
  InfoCircle,
  BarCode,
  Photo,
  Avatar,
  Income,
  Expense,
  PresentationChart,
  CalendarFact,
} from "../assets/images/icons/Icons";

const iconsMap = {
  dashboard: <Dashboard />,
  clients: <Clients />,
  calendar: <Calendar />,
  calendarFact: <CalendarFact />,
  products: <Products />,
  leads: <Leads />,
  toggleClose: <ToggleClose />,
  toggleOpen: <ToggleOpen />,
  search: <Search />,
  telephone: <Telephone />,
  notification: <Notification />,
  tickCircle: <TickCircle />,
  close: <Close />,
  closeCircle: <CloseCircle />,
  infoCircle: <InfoCircle />,
  barCode: <BarCode />,
  photo: <Photo />,
  avatar: <Avatar />,
  income: <Income />,
  expense: <Expense />,
  presentationChart: <PresentationChart />,
};

export default iconsMap;
