import {
  Calendar,
  Clients,
  Dashboard,
  Leads,
  Products,
  ToggleClose,
  ToggleOpen,
  Search,
  Telephone,
  Notification,
  TickCircle,
  Close,
  CloseCircle,
  InfoCircle,
  BarCode,
  Photo,
  Avatar,
  Income,
  Expense,
  PresentationChart,
  CalendarFact,
  Send,
  CalendarDays,
  Email,
  ArrowUp,
  ArrowDown,
  ArrowRight,
  ArrowLeft,
  AvatarFilled,
  TelephoneFilled,
  BarCodeFilled,
  DoubleTick,
  AddCircle,
  Clock,
  ArrowRightLong,
  MoneyAdd,
  CardFilled,
  Wallet,
  WalletFilled,
  Refresh,
  Lock,
  Logout,
  LogoutFilled,
  CalendarFilled,
  Delete,
  DeleteFilled,
  Edit,
  EditFilled,
  ExcelFile,
  Eye,
  EyeClosed,
  Filter,
  FilterFilled,
  MenuDots,
  Messenger,
  MessengerFilled,
  Mic,
  MicFilled,
  PauseCircleFilled,
  PdfFile,
  Pencil,
  StopCircle,
  StopCircleFilled,
  Download,
  DownloadFilled,
  Sun,
  Moon,
  Monitor,
  ChatBubble,
  Facebook,
  Leaf,
  Users,
  Globe,
  Meta,
} from '@assets/images/icons/Icons';

const iconsMap = {
  dashboard: <Dashboard />,
  clients: <Clients />,
  calendar: <Calendar />,
  calendarFilled: <CalendarFilled />,
  calendarFact: <CalendarFact />,
  products: <Products />,
  leads: <Leads />,
  toggleClose: <ToggleClose />,
  toggleOpen: <ToggleOpen />,
  search: <Search />,
  telephone: <Telephone />,
  notification: <Notification />,
  tickCircle: <TickCircle />,
  addCircle: <AddCircle />,
  doubleTick: <DoubleTick />,
  close: <Close />,
  clock: <Clock />,
  closeCircle: <CloseCircle />,
  infoCircle: <InfoCircle />,
  barCode: <BarCode />,
  barCodeFilled: <BarCodeFilled />,
  photo: <Photo />,
  avatar: <Avatar />,
  avatarFilled: <AvatarFilled />,
  income: <Income />,
  expense: <Expense />,
  wallet: <Wallet />,
  walletFilled: <WalletFilled />,
  cardFilled: <CardFilled />,
  presentationChart: <PresentationChart />,
  send: <Send />,
  calendarDays: <CalendarDays />,
  email: <Email />,
  arrowUp: <ArrowUp />,
  arrowDown: <ArrowDown />,
  arrowRight: <ArrowRight />,
  arrowRightLong: <ArrowRightLong />,
  arrowLeft: <ArrowLeft />,
  telephoneFilled: <TelephoneFilled />,
  moneyAdd: <MoneyAdd />,
  refresh: <Refresh />,
  lock: <Lock />,
  logout: <Logout />,
  logoutFilled: <LogoutFilled />,
  eye: <Eye />,
  eyeClosed: <EyeClosed />,
  menuDots: <MenuDots />,
  messenger: <Messenger />,
  messengerFilled: <MessengerFilled />,
  edit: <Edit />,
  editFilled: <EditFilled />,
  pencil: <Pencil />,
  delete: <Delete />,
  deleteFilled: <DeleteFilled />,
  filter: <Filter />,
  filterFilled: <FilterFilled />,
  pdfFile: <PdfFile />,
  excelFile: <ExcelFile />,
  mic: <Mic />,
  micFilled: <MicFilled />,
  stopCircle: <StopCircle />,
  stopCircleFilled: <StopCircleFilled />,
  pauseCircleFilled: <PauseCircleFilled />,
  download: <Download />,
  downloadFilled: <DownloadFilled />,
  sun: <Sun />,
  moon: <Moon />,
  monitor: <Monitor />,
  chatBubble: <ChatBubble />,
  facebook: <Facebook />,
  leaf: <Leaf />,
  users: <Users />,
  globe: <Globe />,
  meta: <Meta />,
};

export default iconsMap;
