import {
  Calendar,
  Clients,
  Dashboard,
  Leads,
  Products,
  ToggleClose,
  ToggleOpen,
  Search,
  Telephone,
  Notification,
  TickCircle,
  Close,
  CloseCircle,
  InfoCircle,
  BarCode,
  Photo,
  Avatar,
  Income,
  Expense,
  PresentationChart,
  CalendarFact,
  Send,
  CalendarDays,
  Email,
  ArrowUp,
  ArrowDown,
  ArrowRight,
  ArrowLeft,
  AvatarFilled,
  TelephoneFilled,
  BarCodeFilled,
  DoubleTick,
  AddCircle,
  Clock,
  ArrowRightLong,
  MoneyAdd,
  CardFilled,
  Wallet,
  WalletFilled,
  Refresh,
  Lock,
  Logout,
  LogoutFilled,
} from "@assets/images/icons/Icons";
import {
  CalendarFilled,
  Delete,
  DeleteFilled,
  Edit,
  EditFilled,
  Eye,
  EyeClosed,
  MenuDots,
  Messenger,
  MessengerFilled,
  Pencil,
} from "../assets/images/icons/Icons";

const iconsMap = {
  dashboard: <Dashboard />,
  clients: <Clients />,
  calendar: <Calendar />,
  calendarFilled: <CalendarFilled />,
  calendarFact: <CalendarFact />,
  products: <Products />,
  leads: <Leads />,
  toggleClose: <ToggleClose />,
  toggleOpen: <ToggleOpen />,
  search: <Search />,
  telephone: <Telephone />,
  notification: <Notification />,
  tickCircle: <TickCircle />,
  addCircle: <AddCircle />,
  doubleTick: <DoubleTick />,
  close: <Close />,
  clock: <Clock />,
  closeCircle: <CloseCircle />,
  infoCircle: <InfoCircle />,
  barCode: <BarCode />,
  barCodeFilled: <BarCodeFilled />,
  photo: <Photo />,
  avatar: <Avatar />,
  avatarFilled: <AvatarFilled />,
  income: <Income />,
  expense: <Expense />,
  wallet: <Wallet />,
  walletFilled: <WalletFilled />,
  cardFilled: <CardFilled />,
  presentationChart: <PresentationChart />,
  send: <Send />,
  calendarDays: <CalendarDays />,
  email: <Email />,
  arrowUp: <ArrowUp />,
  arrowDown: <ArrowDown />,
  arrowRight: <ArrowRight />,
  arrowRightLong: <ArrowRightLong />,
  arrowLeft: <ArrowLeft />,
  telephoneFilled: <TelephoneFilled />,
  moneyAdd: <MoneyAdd />,
  refresh: <Refresh />,
  lock: <Lock />,
  logout: <Logout />,
  logoutFilled: <LogoutFilled />,
  eye: <Eye />,
  eyeClosed: <EyeClosed />,
  menuDots: <MenuDots />,
  messenger: <Messenger />,
  messengerFilled: <MessengerFilled />,
  edit: <Edit />,
  editFilled: <EditFilled />,
  pencil: <Pencil />,
  delete: <Delete />,
  deleteFilled: <DeleteFilled />,
};

export default iconsMap;
